/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Fri Feb 21 22:28:55 2020. */

#ifndef PB_ZINGUOCONFIG_PB_H_INCLUDED
#define PB_ZINGUOCONFIG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ZinguoConfigMessage {
    bool dual_motor;
    bool dual_warm;
    uint8_t delay_blow;
    uint8_t linkage;
    uint8_t max_temp;
    uint8_t close_warm;
    uint8_t close_ventilation;
    bool beep;
    bool reverse_led;
    uint16_t report_interval;
/* @@protoc_insertion_point(struct:ZinguoConfigMessage) */
} ZinguoConfigMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ZinguoConfigMessage_init_default         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ZinguoConfigMessage_init_zero            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ZinguoConfigMessage_dual_motor_tag       1
#define ZinguoConfigMessage_dual_warm_tag        2
#define ZinguoConfigMessage_delay_blow_tag       3
#define ZinguoConfigMessage_linkage_tag          4
#define ZinguoConfigMessage_max_temp_tag         5
#define ZinguoConfigMessage_close_warm_tag       6
#define ZinguoConfigMessage_close_ventilation_tag 7
#define ZinguoConfigMessage_beep_tag             8
#define ZinguoConfigMessage_reverse_led_tag      9
#define ZinguoConfigMessage_report_interval_tag  10

/* Struct field encoding specification for nanopb */
extern const pb_field_t ZinguoConfigMessage_fields[11];

/* Maximum encoded size of messages (where known) */
#define ZinguoConfigMessage_size                 44

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ZINGUOCONFIG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
