/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Sun Sep 13 08:43:51 2020. */

#include "ZinguoConfig.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ZinguoConfigMessage_fields[16] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, ZinguoConfigMessage, dual_motor, dual_motor, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, dual_warm, dual_motor, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, delay_blow, dual_warm, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, linkage, delay_blow, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, max_temp, linkage, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, close_warm, max_temp, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, close_ventilation, close_warm, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, beep, close_ventilation, 0),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, reverse_led, beep, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, report_interval, reverse_led, 0),
    PB_FIELD( 11, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, led_type, report_interval, 0),
    PB_FIELD( 12, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, led_start, led_type, 0),
    PB_FIELD( 13, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, led_end, led_start, 0),
    PB_FIELD( 14, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, led_light, led_end, 0),
    PB_FIELD( 15, UINT32  , SINGULAR, STATIC  , OTHER, ZinguoConfigMessage, led_time, led_light, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
